### ISSUE TITLE
Masthead example css bug

### ISSUE THREAD

**Issue by iemand002** [ConciseCSS/concisecss.github.io#36]
on line 40 of masthead.css it should be
```css
.siteContent {
    padding: 50px 15px;
}
```
so it does not show a horizontal scrollbar on screens < 1246px
